from tools import *
import os
from dotenv import load_dotenv
from autogen import ConversableAgent
from autogen import register_function
from autogen import GroupChatManager, GroupChat


load_dotenv()


"""Create agents"""

img_generator = ConversableAgent(
    name="Image_Generator",
    system_message="""
    You are a world class AI image prompt engineer, 
    you will be given an image of a cloth, and text prompt (either original prompt or the iterated prompt from image reviewer)
    with the information given, you will use genenrate_img to generate a realistic photo of a person wearing that specific cloth.chat_messages=

    You will continuously iterate images based on feedback from img_reviewer until the img_reviewer is satisfied with the result
    """,
    llm_config={
        "config_list": [
            {
                "model": "gpt-4o",
                "api_key": os.environ["OPENAI_API_KEY"],
            }
        ],
        "timeout": 120,
    },
)

img_reviewer = ConversableAgent(
    name="Image_Reviewer",
    system_message="""
    You will review both the original_cloth_img as well as the image generated by the img_generator based on the img urls,
    classify if the cloth in the image from img_generator is 95% match with the original cloth image.
    If it is more than 95% match, just return "95% match", if it is not 95% match, list out the discrepancies, and generate
    an iterated text prompt for the image generation model to fill the gap of discrepancy.
    """,
    llm_config={
        "config_list": [
            {
                "model": "gpt-4o",
                "api_key": os.environ["OPENAI_API_KEY"],
            }
        ],
        "timeout": 120,
    },
    is_termination_msg=lambda msg: "95% match" in msg["content"].lower(),
)

img_finetuner = ConversableAgent(
    name="Image_Finetuner",
    system_message="""
    You will convert the image generated and approved by img_generator and img_reviewer into a high quality image, fix hand distortion and upscale
    the final image, after the image is upscaled, return "TERMINATE" to end the conversation.
    """,
    llm_config={
        "config_list": [
            {
                "model": "gpt-4o",
                "api_key": os.environ["OPENAI_API_KEY"],
            }
        ],
        "timeout": 120,
    },
    is_termination_msg=lambda msg: "terminate" in msg["content"].lower(),
)

user_proxy = ConversableAgent(
    name="User",
    llm_config={
        "config_list": [
            {
                "model": "gpt-4-turbo",
                "api_key": os.environ["OPENAI_API_KEY"],
            }
        ],
        "timeout": 120,
    },
    is_termination_msg=lambda msg: msg.get("content") is not None
    and "TERMINATE" in msg["content"],
    human_input_mode="NEVER"
)

# Register functions
register_function(
    generate_img,
    caller=img_generator,
    executor=user_proxy,
    name="generate_img",
    description="generate image with AI model based on an original cloth image and a text prompt"
)

register_function(
    review_img,
    caller=img_reviewer,
    executor=user_proxy,
    name="review_img",
    description="compare and review image"
)

register_function(
    fix_hands,
    caller=img_finetuner,
    executor=user_proxy,
    name="fix_hands",
    description="Fix AI image hand distortion with a special AI model"
)

register_function(
    upscale_image,
    caller=img_finetuner,
    executor=user_proxy,
    name="upscale_img",
    description="upscale image to make it high qualiy"
)

# Create and trigger group chat
group_chat= GroupChat(
    agents=[img_generator, img_reviewer, user_proxy],
    messages = [],
    max_round=7,
)

group_chat_manager = GroupChatManager(
    groupchat=group_chat,
    llm_config={
        "config_list": [{"model": "gpt-4", "api_key": os.environ["OPENAI_API_KEY"]}]
    },
)

base_prompt = "a woman with red hair, wear a blue jacket, in a cafe in paris"
cloth_img = ""


chat_result = user_proxy.initiate_chats(
  [
   {
    "recipient": group_chat_manager,
    "message": f"""
        **original_cloth_img**: {cloth_img}
        **base prompt**: {base_prompt}
        ----
        Generate a realistic photo based on the original cloth image and base prompt above that pass 100% match from img_reviewer.
        """,
        "summary_method": "reflection_with_llm",
        "summary_args": {
            "summary_prompt": "Including the latest_ai_img_url, as well as the original_cloth_img, latest_prompt"
        },
   },
   {
       "recipient": img_finetuner,
       "message": "Finetune the latest AI generated image, fixing hand distortion if there is any, and then upscale the image that returned fix_hands to make it high quality.",
   },
  ]
 )


